name: vvin
description: VVIN CRM Platform.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+17

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pull_to_refresh: ^1.5.8
  scalable_image: ^1.1.2
  bouncing_widget: ^1.2.0
  empty_widget: ^0.0.1
  cached_network_image: ^2.0.0
  flutter_native_image: ^0.0.5+2
  flutter_web_browser: ^0.11.0
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.3+1
  flutter_open_whatsapp: ^0.1.2
  open_file: ^2.1.1
  url_launcher: ^5.4.1
  device_info: ^0.4.1+4
  connectivity: ^0.4.6+1
  path_provider: ^1.5.1
  sqflite: ^1.2.0
  syncfusion_flutter_charts: ^1.0.0-beta.3
  firebase_messaging: ^6.0.9
  intl: ^0.16.0
  progress_indicators: ^0.1.4
  toast: ^0.1.5
  uni_links: ^0.2.0
  webview_flutter: ^0.3.19+9
  http: ^0.12.0+2
  shared_preferences: ^0.5.3
  flutter_launcher_icons: ^0.7.4
  permission_handler: ^4.2.0+hotfix.3
  flutter_screenutil: ^1.0.2
  firebase_ml_vision: ^0.9.3+5
  network_to_file_image: ^2.2.4
  loading_indicator: ^1.1.0
  flutter_spinkit: ^4.1.2
  package_info: ^0.4.0+14
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:  
  image_path: 'assets/images/vvin.png'
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
